version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/simple_branching/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:10.10
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=simple_branching_dev
      - POSTGRES_PASSWORD=simple_branching_dev
      - POSTGRES_DB=simple_branching_db

volumes:
  postgres_data: