# Generated by Django 2.2.7 on 2019-11-09 13:41

import branches.utils
from django.db import migrations, models
import simple_branching.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "facade",
                    models.ImageField(
                        storage=simple_branching.storage_backends.MediaStorage(),
                        upload_to=branches.utils.upload_facade_to,
                        verbose_name="Facade",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={"verbose_name_plural": "branches"},
        )
    ]
