# Generated by Django 2.2.7 on 2019-11-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("branches", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "permissions": [("edit_coordinates", "Can edit coordinates")],
                "verbose_name_plural": "branches",
            },
        )
    ]
